services:
  app:
    image: python:3.10-slim
    volumes:
      - .:/backend
    working_dir: /backend
    command: bash -c "python -m venv /venv && /venv/bin/pip install -r requirements.txt && /venv/bin/python main.py"
    ports:
      - "8000:8000"
    env_file:
      - .env
